package com.zemoso.zinteract.util;

/**
 * Created by Praveen on 18-Dec-14.
 */
public enum StringConstants {

    DATATYPE_STRING,
    DATATYPE_LONG,
    DATATYPE_DOUBLE,
    DATATYPE_DATE,
    DATATYPE_BOOLEAN,
    CONDITION_LESS_THAN,
    CONDITION_GREATER_THAN,
    CONDITION_EQUALS,
    CONDITION_LESS_THAN_EQUALS,
    CONDITION_NOT_EQUALS,
    CONDITION_GREATER_THAN_EQUALS,
    CONDITION_BETWEEN,
    CONDITION_IN,
    CONDITION_NOT_IN,
    COMPARATOR_LESS_THAN,
    COMPARATOR_GREATER_THAN,
    COMPARATOR_EQUALS,
    COMPARATOR_LESS_THAN_EQUALS,
    COMPARATOR_NOT_EQUALS,
    COMPARATOR_GREATER_THAN_EQUALS,
    COMPARATOR_BETWEEN,
    COMPARATOR_IN,
    COMPARATOR_NOT_IN,
    COMPARATOR_LIKE,
    COMPARATOR_NOT_LIKE
}
