package com.zemoso.zinteract.decisiontable;

/**
 * Created by Praveen on 18-Dec-14.
 */
public enum StringConstants {
    DATATYPE_STRING, DATATYPE_LONG, DATATYPE_DOUBLE, DATATYPE_DATE,DATATYPE_BOOLEAN, CONDITION_LESSTHAN, CONDITION_GREATERTHAN,
    CONDITION_EQUALS, CONDITION_LESSTHAN_EQUALS, CONDITION_NOT_EQUALS, CONDITION_GREATERTHAN_EQUALS,
    CONDITION_BETWEEN, CONDITION_IN, CONDITION_NOTIN, COMPARATOR_LESSTHAN, COMPARATOR_GREATERTHAN,
    COMPARATOR_EQUALS, COMPARATOR_LESSTHAN_EQUALS, COMPARATOR_NOT_EQUALS, COMPARATOR_GREATERTHAN_EQUALS,
    COMPARATOR_BETWEEN, COMPARATOR_IN, COMPARATOR_NOTIN, COMPARATOR_LIKE, COMPARATOR_NOT_LIKE
}
